### Satyajeet Tukaram Chavan
### Roll no-381025
### PRN no-22310630
### Batch-A1

Perform bag-of-words approach (count occurrence, normalized count occurrence), TF-IDF on
data. Create embeddings using Word2Vec

In [ ]:
pip install nltk scikit-learn gensim


   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 27.9/27.9 MB 69.2 MB/s eta 0:00:00


In [ ]:
import nltk
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer, TfidfTransformer
from gensim.models import Word2Vec
from nltk.tokenize import word_tokenize

In [ ]:
# Download required NLTK data
nltk.download('punkt')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


True

In [ ]:
# Sample dataset (you can replace this with your own data)
corpus = [
"Natural Language Processing is a fascinating field",
"NLTK and Gensim are useful libraries for NLP",
"Machine learning helps computers understand language",
"Word embeddings capture semantic meaning",
"TF IDF and Bag of Words are basic text features"
]

In [ ]:
print("Original Corpus:")
for i, doc in enumerate(corpus, 1):
 print(f"{i}. {doc}")

Original Corpus:
1. Natural Language Processing is a fascinating field
2. NLTK and Gensim are useful libraries for NLP
3. Machine learning helps computers understand language
4. Word embeddings capture semantic meaning
5. TF IDF and Bag of Words are basic text features


In [ ]:
# 1. Bag-of-Words (Count Occurrence)
# -------------------------------
count_vectorizer = CountVectorizer()
bow_counts = count_vectorizer.fit_transform(corpus)


print("\nBag-of-Words (Count Occurrence):")
print(bow_counts.toarray())
print("Feature Names:")
print(count_vectorizer.get_feature_names_out())


Bag-of-Words (Count Occurrence):
[[0 0 0 0 0 0 0 1 0 1 0 0 0 0 1 1 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0]
 [1 1 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 1 0 0 0 1 1 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 1 0 0 0 0 0 0 1 0 0 1 1 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 1 0]
 [1 1 1 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 0 0 1 1 0 0 0 1]]
Feature Names:
['and' 'are' 'bag' 'basic' 'capture' 'computers' 'embeddings'
 'fascinating' 'features' 'field' 'for' 'gensim' 'helps' 'idf' 'is'
 'language' 'learning' 'libraries' 'machine' 'meaning' 'natural' 'nlp'
 'nltk' 'of' 'processing' 'semantic' 'text' 'tf' 'understand' 'useful'
 'word' 'words']


In [ ]:
# 2. Normalized Bag-of-Words
# -------------------------------
count_vectorizer_norm = CountVectorizer()
bow_counts_for_norm = count_vectorizer_norm.fit_transform(corpus)

tfidf_transformer = TfidfTransformer(use_idf=False, norm='l2')
bow_normalized = tfidf_transformer.fit_transform(bow_counts_for_norm)

print("\nNormalized Bag-of-Words (L2 Norm):")
print(bow_normalized.toarray())


Normalized Bag-of-Words (L2 Norm):
[[0.         0.         0.         0.         0.         0.
  0.         0.40824829 0.         0.40824829 0.         0.
  0.         0.         0.40824829 0.40824829 0.         0.
  0.         0.         0.40824829 0.         0.         0.
  0.40824829 0.         0.         0.         0.         0.
  0.         0.        ]
 [0.35355339 0.35355339 0.         0.         0.         0.
  0.         0.         0.         0.         0.35355339 0.35355339
  0.         0.         0.         0.         0.         0.35355339
  0.         0.         0.         0.35355339 0.35355339 0.
  0.         0.         0.         0.         0.         0.35355339
  0.         0.        ]
 [0.         0.         0.         0.         0.         0.40824829
  0.         0.         0.         0.         0.         0.
  0.40824829 0.         0.         0.40824829 0.40824829 0.
  0.40824829 0.         0.         0.         0.         0.
  0.         0.         0.         0.     

In [ ]:
# 3. TF-IDF (Term Frequency-Inverse Document Frequency)
# --------------------------------------------------
tfidf_vectorizer = TfidfVectorizer()
tfidf_matrix = tfidf_vectorizer.fit_transform(corpus)

print("\nTF-IDF Matrix:")
print(tfidf_matrix.toarray())
print("Feature Names (TF-IDF):")
print(tfidf_vectorizer.get_feature_names_out())


TF-IDF Matrix:
[[0.         0.         0.         0.         0.         0.
  0.         0.42066906 0.         0.42066906 0.         0.
  0.         0.         0.42066906 0.33939315 0.         0.
  0.         0.         0.42066906 0.         0.         0.
  0.42066906 0.         0.         0.         0.         0.
  0.         0.        ]
 [0.29857028 0.29857028 0.         0.         0.         0.
  0.         0.         0.         0.         0.37007017 0.37007017
  0.         0.         0.         0.         0.         0.37007017
  0.         0.         0.         0.37007017 0.37007017 0.
  0.         0.         0.         0.         0.         0.37007017
  0.         0.        ]
 [0.         0.         0.         0.         0.         0.42066906
  0.         0.         0.         0.         0.         0.
  0.42066906 0.         0.         0.33939315 0.42066906 0.
  0.42066906 0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.42066906 0.
  

In [ ]:
# 4. Word2Vec Embeddings
# -------------------------------
# Tokenize corpus
tokenized_corpus = [word_tokenize(doc.lower()) for doc in corpus]

In [ ]:
# Train Word2Vec model
word2vec_model = Word2Vec(tokenized_corpus, vector_size=100, window=5, min_count=1, workers=4)

print("\nWord2Vec Model Trained.")

# Example: Get embedding for a word
if 'language' in word2vec_model.wv:
    print("\nEmbedding for 'language':")
    print(word2vec_model.wv['language'])

# Example: Find most similar words
if 'language' in word2vec_model.wv:
    print("\nWords most similar to 'language':")
    print(word2vec_model.wv.most_similar('language'))


Word2Vec Model Trained.

Embedding for 'language':
[ 9.3217925e-05  3.0777205e-03 -6.8114577e-03 -1.3711961e-03
  7.6678363e-03  7.3385513e-03 -3.6672817e-03  2.6534828e-03
 -8.3205597e-03  6.1965222e-03 -4.6336860e-03 -3.1653163e-03
  9.3114022e-03  8.7925693e-04  7.4929553e-03 -6.0722707e-03
  5.1641441e-03  9.9267988e-03 -8.4607024e-03 -5.1381774e-03
 -7.0598871e-03 -4.8623248e-03 -3.7750429e-03 -8.5290810e-03
  7.9560699e-03 -4.8423950e-03  8.4230630e-03  5.2665914e-03
 -6.5490673e-03  3.9536874e-03  5.4720147e-03 -7.4247816e-03
 -7.4070757e-03 -2.4801653e-03 -8.6230347e-03 -1.5786547e-03
 -3.9272258e-04  3.2925415e-03  1.4375689e-03 -8.8077754e-04
 -5.5948677e-03  1.7290696e-03 -8.9702714e-04  6.7909225e-03
  3.9776331e-03  4.5299693e-03  1.4313816e-03 -2.6992778e-03
 -4.3622991e-03 -1.0327762e-03  1.4375491e-03 -2.6472486e-03
 -7.0811724e-03 -7.8063812e-03 -9.1194492e-03 -5.9319953e-03
 -1.8469368e-03 -4.3250942e-03 -6.4575053e-03 -3.7153910e-03
  4.2891768e-03 -3.7354406e-03  8

In [ ]:
# Download required NLTK data for word_tokenize
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.


True

In [ ]:
# Get sentence embedding (average of word vectors)
def sentence_embedding(sentence, model):
    tokens = word_tokenize(sentence.lower())
    vectors = [model.wv[word] for word in tokens if word in model.wv]
    if len(vectors) == 0:
        return np.zeros(model.vector_size)
    return np.mean(vectors, axis=0)

sample_sentence = "Natural language processing"
embedding = sentence_embedding(sample_sentence, word2vec_model)

print(f"\nSentence embedding for: '{sample_sentence}'")
print(embedding)


Sentence embedding for: 'Natural language processing'
[ 1.43745320e-03 -5.19340346e-03 -1.62053725e-03 -3.62594059e-04
  2.73544085e-03  2.65763607e-04 -5.79310348e-03 -2.21614420e-04
  3.13446228e-03 -1.23969431e-03  3.25390627e-03 -1.06587075e-04
  3.93592147e-03  8.79614439e-04  4.25744336e-03 -1.01842918e-03
  9.04095650e-04  1.03478087e-04  1.20514247e-03 -3.23425676e-03
 -3.97296483e-03 -8.87365080e-04  1.80697720e-03 -6.99928962e-03
  7.22442335e-03 -1.17927336e-03  1.76682090e-03  6.77613169e-03
 -2.14114063e-03  6.61642430e-03  1.21497619e-03 -2.90035270e-03
  1.49896333e-03 -3.90145765e-03 -2.54906248e-03  1.23761885e-03
 -2.04229332e-03 -3.07604484e-03  2.15400965e-03 -1.16786733e-03
 -8.49742442e-04 -4.97345021e-03  4.45992831e-04  6.83927152e-04
  6.75586984e-03  9.49405730e-05  6.86252955e-04  6.33082018e-05
 -1.60222093e-03 -6.96582720e-04  2.03142525e-03  2.07272042e-05
  1.11112930e-03 -1.28784601e-03 -2.81527825e-03 -1.59515406e-03
 -2.25661276e-03  3.04877083e-03 -2